"""Add name_clean, title_clean, birth_date_iso, needs_review column to directors table

Revision ID: cf1fd456b938
Revises: a8655283791f
Create Date: 2025-04-22 20:20:14.290781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf1fd456b938"
down_revision: Union[str, None] = "a8655283791f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("directors", sa.Column("name_clean", sa.String(), nullable=True))
    op.add_column("directors", sa.Column("title_clean", sa.String(), nullable=True))
    op.add_column("directors", sa.Column("birth_date_iso", sa.String(), nullable=True))
    op.add_column(
        "directors",
        sa.Column(
            "needs_review", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("directors", "needs_review")
    op.drop_column("directors", "birth_date_iso")
    op.drop_column("directors", "title_clean")
    op.drop_column("directors", "name_clean")
    # ### end Alembic commands ###
